const theme = {
  light: {
    theme: "light",
    bg: "#FFFFFF",
    background: "#1F4690",
    itembackground:"#F8F9FE",
    txt: "#000000",
    icon: "#9F0CE3",
    box: "#E3E7EC",
    barstyle: "dark-content",
    // img: require("../../assets/image/Progress.png"),
    // banner: require("../../assets/image/banner.png"),
    apple: require("../../assets/img/Apple.png"),
    // boarding: require("../../assets/image/BG1.png"),
    line: require("../../assets/img/blueline1.png"),
    // msg: require("../../assets/image/d1.png"),
    fpb: "#F5F5F5",
    chat: "#E3E7EC",
  },
  dark: {
    theme: "dark",
    bg: "#111111",
    background: "#000000",
    itembackground:"#1B2128",
    txt: "#FFFFFF",
    icon: "#00C2CB",
    box: "#1E1E1E",
    barstyle: "light-content",
    // img: require("../../assets/image/Progressblack.png"),
    // banner: require("../../assets/img/banner1.png"),
    apple: require("../../assets/img/Apple1.png"),
    // boarding: require("../../assets/img/BG.png"),
    line: require("../../assets/img/orangeline1.png"),
    // msg: require("../../assets/img/d2.png"),
    fpb: "#434E58",
    chat: "#171725",
  },
};

export default theme;
